### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by saifellafi** [custora/bee#1]
Hi,

I am wondering which g++ compiler does this package need, as I am getting this error.

$ R CMD INSTALL -l /apps/stuff/R/library bee_1.0.tar.gz
- installing _source_ package ‘bee’ ...
  *\* libs
  g++ -I/usr/lib64/RRO-8.0.1/R-3.1.2/lib64/R/include -DNDEBUG -std=gnu++11 -I../inst/include -I../inst/include/tcli_thrift -Wno-macro-redefined -I/usr/local/include -I"/apps/stuff/R/library/Rcpp/include" -I"/apps/stuff/R/library/BH/include"   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
  cc1plus: error: unrecognized command line option "-std=gnu++11"
  cc1plus: warning: unrecognized command line option "-Wno-macro-redefined"
  make: **\* [RcppExports.o] Error 1
  ERROR: compilation failed for package ‘bee’
- removing ‘/apps/stuff/R/library/bee’

Thanks,
Saif

**Comment by saifellafi** [comment]
Having my compiler up to date and reinstalled Rcpp and dplyr, now I am getting the following when compiling:

/opt/stuff/gcc/include/c++/5.2.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
extension.cpp: In function ‘Rcpp::XPtrBee::Client bee_disconnect(SEXP)’:
extension.cpp:21:37: error: ‘class Rcpp::XPtrBee::Client’ has no member named ‘ge ’
   Bee::Client *client = client_xptr.get();
                                     ^
extension.cpp: In function ‘Rcpp::XPtrBee::Client bee_execute(SEXP, std::__cxx11::string)’:
extension.cpp:29:37: error: ‘class Rcpp::XPtrBee::Client’ has no member named ‘ge ’
   Bee::Client *client = client_xptr.get();
                                     ^
extension.cpp: In function ‘Rcpp::List bee_fetch(SEXP, int)’:
extension.cpp:37:37: error: ‘class Rcpp::XPtrBee::Client’ has no member named ‘ge ’
   Bee::Client *client = client_xptr.get();
                                     ^
extension.cpp: In function ‘bool bee_has_more_rows(SEXP)’:
extension.cpp:44:37: error: ‘class Rcpp::XPtrBee::Client’ has no member named ‘ge ’
   Bee::Client *client = client_xptr.get();

**Comment by saifellafi** [comment]
I got further ahead by updating Rcpp to 0.12 manually. Now I have some issues with thrift libraries :-)

**Comment by oggy** [comment]
Thanks for the report @saifellafi !

I just discovered this myself today -- I believe it's because the Thrift project released an update recently. You can try compiling with Thrift 0.9.2, or else I'll hopefully get around to pushing a fix soon.

**Comment by saifellafi** [comment]
Thank you, I was hitting my head against a wall :-)
Will let you know if it works with 0.9.2

I am getting this error when compiling 0.9.2. Any ideas? 
Tried disabling python and lua make[4]: Entering directory /opt/cmor/thrift/lib/cpp/test' depbase=echo processor/ProcessorTest.o | sed 's|[^/]*$|.deps/&|;s|.o$||'`;\ g++ -DHAVE_CONFIG_H -I. -I../../.. -I../../../lib/cpp/src/thrift -I/opt/cmor/boost/include -I../../../lib/cpp/src -I/opt/cmor/thrift_build/include -Wall -Wextra -pedantic -g -O2 -std=c++11 -MT processor/ProcessorTest.o -MD -MP -MF $depbase.Tpo -c -o processor/ProcessorTest.o processor/ProcessorTest.cpp &&\ mv -f $depbase.Tpo $depbase.Po In file included from processor/ProcessorTest.cpp:34:0: ../../../lib/cpp/src/thrift/server/TNonblockingServer.h:40:19: fatal error: event.h: No such file or directory compilation terminated.

Saif

**Comment by saifellafi** [comment]
I am getting this error when compiling 0.9.2. Any ideas? Tried disabling python and lua

make[4]: Entering directory `/opt/cmor/thrift/lib/cpp/test'
depbase=`echo processor/ProcessorTest.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        g++ -DHAVE_CONFIG_H -I. -I../../.. -I../../../lib/cpp/src/thrift  -I/opt/cmor/boost/include -I../../../lib/cpp/src -I/opt/cmor/thrift_build/include -Wall -Wextra -pedantic -g -O2 -std=c++11 -MT processor/ProcessorTest.o -MD -MP -MF $depbase.Tpo -c -o processor/ProcessorTest.o processor/ProcessorTest.cpp &&\
        mv -f $depbase.Tpo $depbase.Po
In file included from processor/ProcessorTest.cpp:34:0:
../../../lib/cpp/src/thrift/server/TNonblockingServer.h:40:19: fatal error: event.h: No such file or directory
compilation terminated.

**Comment by oggy** [comment]
I think you either need to install libevent (the -dev package if you're on
Debian/Ubuntu/etc), or ensure R can find it by setting something like this
in your ~/.R/Makevars

```
CXXFLAGS += -I/path/to/libevent/include
```

**Comment by saifellafi** [comment]
Thanks, this was thrift so I added to CPPFLAGS. It went a little bit further until:

make[4]: **\* No rule to make target `../../../lib/cpp/libthriftnb.la', needed by`processor_test'.  Stop.

**Comment by saifellafi** [comment]
Well, the issue has been fixed in 0.9.3 so it is somewhat problematic :/

https://issues.apache.org/jira/browse/THRIFT-2910

edit: I think this was to build it without libevent. I will reconfigure using --with-libevent and see

**Comment by oggy** [comment]
@saifellafi See if the latest works for you.

**Comment by saifellafi** [comment]
Thank you, thrift 0.9.2 was a pain to compile.

Now I got further ahead with bee, but I am stuck with this issue:

**\* installing help indices
*\* building package indices
*\* testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/opt/stuff/R/x86_64-unknown-linux-gnu-library/3.1/bee/libs/bee.so':
  /opt/stuff/R/x86_64-unknown-linux-gnu-library/3.1/bee/libs/bee.so: undefined symbol: _ZTIN6apache6thrift8protocol9TProtocolE
Error: loading failed
Execution halted
ERROR: loading failed
- removing ‘/opt/stff/R/x86_64-unknown-linux-gnu-library/3.1/bee’
  make: **\* [install] Error 1

Will keep diagnosing my system
Saif

**Comment by oggy** [comment]
That looks like R has found `bee.so`, tried to load it, but couldn't find `thrift.so`. You need to point R at wherever you installed thrift into. You might need to set `LD_LIBRARY_PATH` to include the directory containing `thrift.so`.

**Comment by saifellafi** [comment]
Hmm. That didn’t help. But a couple things:
1. ```
     I have compiled thrift using –without-libevent . I can’t compile it with it using non standard dynamic link locations.
   ```
2. ```
     I dont have thrift.so. I am assuming you speak of libthrift.so. Using LD LIBRARY PATH there didnt work.
   ```
3. ```
     I am assuming the link locations are managed by Rcpp at this point. so I am trying
   ```

PKG_CXXFLAGS=-I"/opt/stuff/thrift_build/include"
PKG_LDFLAGS=-L"/opt/stuff/thrift_build/lib"
PKG_LIBS=-L"/opt/stuff/thrift_build/lib"

Will try with thrift 0.9.2 and see if anything changes

Saif

From: George Ogata [mailto:notifications@github.com]
Sent: Friday, October 16, 2015 12:18 PM
To: custora/bee
Cc: Ellafi, Saif A.
Subject: Re: [bee] Unable to compile (#1)

That looks like R has found bee.so, tried to load it, but couldn't find thrift.so. You need to point R at wherever you installed thrift into. You might need to set LD_LIBRARY_PATH to include the directory containing thrift.so.

—
Reply to this email directly or view it on GitHubhttps://github.com/custora/bee/issues/1#issuecomment-148744046.

**Comment by oggy** [comment]
Yes, I meant `libthrift.so` instead of `thrift.so`.

Ah, you're getting this error when you're building bee, not when loading it in R. In that case, try putting that `LD_LIBRARY_PATH` setting in `~/.R/Makevars`.

**Comment by saifellafi** [comment]
Thanks, but this did not help.

I am sorry I am controlling so many variables, at some point there must be something wrong.
on starters, it is revolution R 8.0.1, I have manually installed newest versions of dplyr, rcpp and BH, and compiled all dependencies my self (even gcc 5.2, and its dependencies).

Not sure where to go on from here though, I have the feeling the issue comes from thrift, as I am having so many issues compiling it, coming from lib-event dependency.
In the end, still getting

Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/opt/cmor/R/x86_64-unknown-linux-gnu-library/3.1/bee/libs/bee.so':
  /opt/cmor/R/x86_64-unknown-linux-gnu-library/3.1/bee/libs/bee.so: undefined symbol: _ZTIN6apache6thrift8protocol9TProtocolE

on R side.
Thanks,
Saif

**Comment by saifellafi** [comment]
Sadly, I give up :(

I have tried different g++ compiler versions, both thrift 0.9.3/2, with and without libevent, different Rcpp, dplyr and HB, releases. and there is no case, it will always throw the undefined symbol in bee.so :/

Only thing “different” so far is that I use RevolutionR instead of standard R.

Hmm.. not sure what else

**Comment by saifellafi** [comment]
This is my thrift compilation output, if you can please verify if I am missing something:

thrift 0.9.2

Building C++ Library ......... : yes
Building C (GLib) Library .... : yes
Building Java Library ........ : no
Building C# Library .......... : no
Building Python Library ...... : yes
Building Ruby Library ........ : no
Building Haskell Library ..... : no
Building Perl Library ........ : no
Building PHP Library ......... : no
Building Erlang Library ...... : no
Building Go Library .......... : no
Building D Library ........... : no
Building NodeJS Library ...... : no
Building Lua Library ......... : yes

C++ Library:
   Build TZlibTransport ...... : yes
   Build TNonblockingServer .. : yes
   Build TQTcpServer (Qt) .... : no

Python Library:
   Using Python .............. : /apps/stuff/anaconda/bin/python

From: Ellafi, Saif A.
Sent: Friday, October 16, 2015 9:37 PM
To: 'custora/bee'; custora/bee
Subject: RE: [bee] Unable to compile (#1)

Sadly, I give up :(

I have tried different g++ compiler versions, both thrift 0.9.3/2, with and without libevent, different Rcpp, dplyr and HB, releases. and there is no case, it will always throw the undefined symbol in bee.so :/

Only thing “different” so far is that I use RevolutionR instead of standard R.

Hmm.. not sure what else

**Comment by oggy** [comment]
FWIW I got it built on Ubuntu just fine using the R provided by `r-base-core`. Added some tips to the readme -- you should pull the latest before trying those instructions.

**Comment by saifellafi** [comment]
Wow! thank you George.

I found my issue!!. The += operator in Makevars was the key. With = operator it seems I was overwriting something else, I needed to append. I was silly, should have known that.

Let see how it goes
Saif
